# custom - add custom configuration

# disable authentication via password and forwarding options
PasswordAuthentication no
AllowAgentForwarding no
AllowTcpForwarding no
X11Forwarding no

# custom - use different port
Port 22222
# custom - display banner, when connecting via ssh
Banner /etc/ssh_banner.net
