# do not load unused kernel modules
## non-native binary support
### also disable systemd service units:
#### "systemd-binfmt.service"
#### "proc-sys-fs-binfmt_misc.automount"
#### "proc-sys-fs-binfmt_misc.mount"
blacklist binfmt_misc

## video and graphics
blacklist drm
blacklist drm_kms_helper
blacklist v3d
blacklist vc4
### camera
blacklist bcm2835_codec
blacklist bcm2835_isp
blacklist bcm2835_v4l2
blacklist vc_sm_cma
### multimedia
blacklist mc
blacklist rpivid_hevc
blacklist v4l2_mem2mem
blacklist videobuf2_common
blacklist videobuf2_dma_contig
blacklist videobuf2_memops
blacklist videobuf2_v4l2
blacklist videodev
### gpu
blacklist i2c_brcmstb
blacklist raspberrypi_gpiomem
blacklist raspberrypi_hwmon

## device drivers
blacklist fuse
blacklist uio
blacklist uio_pdrv_genirq

## sound and audio
blacklist snd_bcm2835
blacklist snd_pcm
blacklist snd_soc_core
blacklist snd_soc_hdmi_codec

## network and wireless
### deactivate wifi
#### also disable systemd service unit: "wpa_supplicant.service"
blacklist brcmfmac
blacklist brcmfmac_wcc
blacklist brcmutil
blacklist cfg80211
blacklist rfkill
